// Sign_in Types
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_FAILED = "SIGNIN_FAILED";

// Activation Types
export const UPDATE_NAME_TOKEN = "UPDATE_NAME_TOKEN";
export const ACCOUNT_ACTIVATION_SUCCESS = "ACCOUNT_ACTIVATION_SUCCESS";
export const ACCOUNT_ACTIVATION_FAILED = "ACCOUNT_ACTIVATION_FAILED";

// Sign_up Types
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILED = "SIGNUP_FAILED";

// Reset Types
export const RESET_SUCCESS = "RESET_SUCCESS";
export const RESET_FAILED = "RESET_FAILED";

// forgot Types
export const FORGOT_SUCCESS = "FORGOT_SUCCESS";
export const FORGOT_FAILED = "FORGOT_FAILED";

// Facebook Types
export const FACEBOOK_SUCCESS = "FACEBOOK_SUCCESS";
export const FACEBOOK_FAILED = "FACEBOOK_FAILED";

// Google Types
export const GOOGLE_SUCCESS = "GOOGLE_SUCCESS";
export const GOOGLE_FAILED = "GOOGLE_FAILED";

//Building
export const UPDATE_STATE_BUILDING = "UPDATE_STATE_BUILDING";
export const GET_HOUSE_ALL_FAILED = "GET_HOUSE_ALL_FAILED";
export const GET_HOUSE_ALL_SUCCESS = "GET_HOUSE_ALL_SUCCESS";

// House
export const UPDATE_STATE_HOUSE = "UPDATE_STATE_HOUSE";
export const GET_HOUSE_FAILED = "GET_HOUSE_FAILED";
export const GET_HOUSE_SUCCESS = "GET_HOUSE_SUCCESS";
export const CREATE_HOUSE_FAILED = "CREATE_HOUSE_FAILED";
export const CREATE_HOUSE_SUCCESS = "CREATE_HOUSE_SUCCESS";
export const DELETE_HOUSE_FAILED = "DELETE_HOUSE_FAILED";
export const DELETE_HOUSE_SUCCESS = "DELETE_HOUSE_SUCCESS";

// Room
export const CREATE_ROOM_FAILED = "CREATE_ROOM_FAILED";
export const CREATE_ROOM_SUCCESS = "CREATE_ROOM_SUCCESS";
export const UPDATE_ROOM_FAILED = "UPDATE_ROOM_FAILED";
export const UPDATE_ROOM_SUCCESS = "UPDATE_ROOM_SUCCESS";
export const DELETE_ROOM_FAILED = "DELETE_ROOM_FAILED";
export const DELETE_ROOM_SUCCESS = "DELETE_ROOM_SUCCESS";

// EQUIPMENT
export const CREATE_EQUIPMENT_FAILED = "CREATE_EQUIPMENT_FAILED";
export const CREATE_EQUIPMENT_SUCCESS = "CREATE_EQUIPMENT_SUCCESS";
export const UPDATE_EQUIPMENT_FAILED = "UPDATE_EQUIPMENT_FAILED";
export const UPDATE_EQUIPMENT_SUCCESS = "UPDATE_EQUIPMENT_SUCCESS";
export const DELETE_EQUIPMENT_FAILED = "DELETE_EQUIPMENT_FAILED";
export const DELETE_EQUIPMENT_SUCCESS = "DELETE_EQUIPMENT_SUCCESS";
export const UPDATE_BUTTON_FAILED = "UPDATE_BUTTON_FAILED";
export const UPDATE_BUTTON_SUCCESS = "UPDATE_BUTTON_SUCCESS";
export const UPDATE_INTENSITY_FAILED = "UPDATE_INTENSITY_FAILED";
export const UPDATE_INTENSITY_SUCCESS = "UPDATE_INTENSITY_SUCCESS";

// REMOTE
export const CREATE_REMOTE_FAILED = "CREATE_REMOTE_FAILED";
export const CREATE_REMOTE_SUCCESS = "CREATE_REMOTE_SUCCESS";
export const UPDATE_REMOTE_FAILED = "UPDATE_REMOTE_FAILED";
export const UPDATE_REMOTE_SUCCESS = "UPDATE_REMOTE_SUCCESS";
export const DELETE_REMOTE_FAILED = "DELETE_REMOTE_FAILED";
export const DELETE_REMOTE_SUCCESS = "DELETE_REMOTE_SUCCESS";
